# IMAGE RECEIVING: "receives" the image from outside Apache Kafka, "stores" it in the
# (client)          image "database," copies the image to the image analysis directory
#                   and sends a Kafka message about it to the image analysis client.
#
#                   NOTE: with the whole application being a MOCK image pipeline, the
#                   received images are generated by this client from a first original
#                   image and the image "database" is actually a directory

from constants.CONSTANTS import *

import os
import shutil

from PIL import Image
    
from kafka import KafkaProducer
import json

# For the MOCK image pipeline, the images to be received are generated here
# from an original image (image # = 0) or from a previously generated image (image # > 0)
def generate_image(image_num):

    prev_image_num = image_num - 1

    # using original image as first generated image
    if image_num == 0:
        prev_image_recv_path      = ""
        image_recv_path           = IMAGE_RECV_DIR + "/" + f"{image_num:05d}" + ".jpg"
        shutil.copy(ORIGINAL_IMAGE_PATH,image_recv_path)

    # generating a second or later image from the previously generated image
    else:
        prev_image_recv_path = IMAGE_RECV_DIR + "/" + f"{prev_image_num:05d}" + ".jpg"
        image_recv_path      = IMAGE_RECV_DIR + "/" + f"{image_num:05d}"      + ".jpg"

        # modify the previous image to generate the new image
        if image_num % 4 == 3:
            print("... Rotating image")
            prev_image = Image.open(prev_image_recv_path)
            rotated_image = prev_image.rotate(90)
            rotated_image.save(image_recv_path)
            rotated_image.close()
            prev_image.close()

        # copy the previous image w/o modification to generate the new image
        else:
            shutil.copy(prev_image_recv_path,image_recv_path)

    return image_recv_path, prev_image_recv_path

# -----------------------------------------------------------------------------------


def receive_image(image_num, image_recv_path, prev_image_recv_path):

    image_db_path       = IMAGE_DB_DIR       + "/" + f"{image_num:05d}" + ".jpg"
    image_analysis_path = IMAGE_ANALYSIS_DIR + "/" + f"{image_num:05d}" + ".jpg"

    # store received image in "database"
    shutil.copy(image_recv_path, image_db_path)
    
    # copy received image to the image analysis directory
    # for the image analysis client to use
    shutil.copy(image_recv_path, image_analysis_path)

    # if not on first image, remove the previous image
    if image_num != 0:
        os.remove(prev_image_recv_path)

    # if receiving the last image
    if image_num == TOTAL_NUM_IMAGES:
        os.remove(image_recv_path)

# ===================================================================================

# Main part of the program
if __name__ == "__main__":

    # Create a Kafka Producer instance
    producer = KafkaProducer(
        bootstrap_servers=['localhost:9092'],  # Replace with your Kafka broker address
        value_serializer=lambda v: json.dumps(v).encode('utf-8') # Serialize messages to JSON bytes
    )

    print()
    print("Starting image receiving client ...")
    print("CODE_DIR = ",CODE_DIR)
    print()

    topic_name = IMAGE_ANALYSIS_TOPIC
    image_num  =  0
    while image_num <= TOTAL_NUM_IMAGES:

        print("Generating Image # = ", image_num)
        image_recv_path, prev_image_recv_path = generate_image(image_num)

        print("Receiving Image  # = ", image_num)
        receive_image(image_num, image_recv_path, prev_image_recv_path)

        # send a Kafka message to the image analysis client
        message_data = {'image_num': image_num}
        producer.send(topic_name, message_data)
        # Flush message to ensure delivery
        producer.flush()

        print(f"Message sent to topic '{topic_name}': {message_data}")
        print()

        image_num += 1

